server:
  port: 8807

spring:
  application:
    name: seckill-server
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  shardingsphere:
    datasource:
      names: seckill
      seckill:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql:3306/seckill
        username: root
        password: root
    rules:
      sharding:
        auto-tables:
          t_seckill_goods:
            actual-data-sources: seckill
            sharding-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: table-mod
        default-table-strategy:
          standard:
            sharding-column: id
            sharding-algorithm-name: MOD
        shardingAlgorithms:
          table-mod:
            type: MOD
            props:
              sharding-count: 2
        default-key-generate-strategy:
          column: id
          key-generator-name: SNOWFLAKE
        default-sharding-column: id
  cloud:
    function:
      definition: placeOrder
    stream:
      bindings:
        placeOrder-out-0:
          destination: place-order