server:
  port: 8888
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: nacos:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://auth-server
          predicates:
            - Path=/**
        - id: account
          uri: lb://account
          predicates:
            - Path=/**
        - id: sms
          uri: lb://sms
          predicates:
            - Path=/**
        - id: goods
          uri: lb://goods-server
          predicates:
            - Path=/**
        - id: order
          uri: lb://order-server
          predicates:
            - Path=/**

