spring:
  profiles: common
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  info:
    env:
      enabled: true
  security:
    enabled: false