server:
  port: 8801

spring:
  application:
    name: account
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  cloud:
    nacos:
      server-addr: nacos:8848
    function:
      definition: backToAvatar
    stream:
      bindings:
        initAvatar-out-0:
          destination: init-avatar
        backToAvatar-in-0:
          destination: back-avatar
  shardingsphere:
    datasource:
      names: account
      account:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql:3306/account
        username: root
        password: root
    rules:
      sharding:
        auto-tables:
          t_account:
            actual-data-sources: account
            sharding-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: table-mod
          t_user:
            actual-data-sources: account
            sharding-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: table-mod
          t_userinfo:
            actual-data-sources: account
            sharding-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: table-mod
        default-table-strategy:
          standard:
            sharding-column: id
            sharding-algorithm-name: MOD
        shardingAlgorithms:
          table-mod:
            type: MOD
            props:
              sharding-count: 2
        default-key-generate-strategy:
          column: id
          key-generator-name: SNOWFLAKE
        default-sharding-column: id
feign:
  httpclient:
    connection-timeout: 5000
