server:
  port: 8801

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  shardingsphere:
    datasource:
      names: account
      account:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.3.127:3306/account
        username: root
        password: root
    rules:
      sharding:
        auto-tables:
          t_account:
            actual-data-sources: account
            sharding-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: table-mod
          t_user:
            actual-data-sources: account
            sharding-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: table-mod
        default-table-strategy:
          standard:
            sharding-column: id
            sharding-algorithm-name: MOD
        shardingAlgorithms:
          table-mod:
            type: MOD
            props:
              sharding-count: 2
        default-key-generate-strategy:
          column: id
          key-generator-name: SNOWFLAKE
        default-sharding-column: id